### PR TITLE
Install on Debian-ish and macOS, take 2

### PR DESCRIPTION
**Pull request by reitzig**
No `if` in composite actions right now, so check OS in shell

### CODE REVIEW

**Comment by reitzig** [comment]
[Green run with the second commit](https://github.com/reitzig/sdkman-for-fish/runs/1747409016?check_suite_focus=true)

It's not ideal, but you _can_ test with a use-case in another repo pointing (on a temporary branch) `uses` to the branch you're working on:

```yaml
      - name: Install fish
        uses: reitzig/install-fish@patch-2
```

You can just re-run the workflow when the branch has changed, it will use the most recent state on each re-run.

Not ideal, alas, but better then nothing.

**Comment by IlanCosman** [comment]
Alright thanks for fixing this.

**Comment by reitzig** [comment]
Hope it works out now! Thanks for your patience and sorry for the hassle!

**Comment by reitzig** [comment]
@IlanCosman , did you want to assign a new tag so new visitors don't pull the broken version?

**Comment by IlanCosman** [comment]
Oh, yeah, thanks for reminding me 😅 I really dislike this system...

**Comment by reitzig** [comment]
Out of curiosity: which system? GitHub? Actions? Using tags for versioning? :thinking:

**Comment by IlanCosman** [comment]
I dislike that as an author you have to update the higher-level tags each time. If I create a `v1.1.1`, I have to also update `v1.1`, and update `v1`. I can't think of a better solution, but it's an an extra thing to keep track of and mess up.

**Comment by reitzig** [comment]
Ah, I see. You're thinking of how Docker does it; Git tags work differently, that's right. You wouldn't expect to have a moving `1.0` tag, but only the "low level" tags. Same for any versioning concept _but_ Docker that I know of, actually. :thinking: (Maven, Ruby gems, ...)

I think some action authors _do_ have these moving tags; I don't think it's necessary. Should be easy to script, anyway. :shrug: 
That said, I think release _branches_ would do what you want. `uses` supports branches!

**Comment by marcransome** [comment]
Sorry to revive a thread on an old pull request, but it was interesting reading and I happen to use the `install-fish` action in several projects. 🐟

I thought it might be useful to point out that there are several actions available on the Marketplace that can be used to move the major and minor tags (e.g. `v1`, `v1.1`) automatically, my personal favourite being [vweevers/additional-tags-action](https://github.com/vweevers/additional-tags-action).

[Here's an example](https://github.com/fish-shop/install-plugin/blob/main/.github/workflows/version.yml) where I use the same action in the context of a workflow triggered by semantic version tags being pushed. It means I only need concern myself with adding the semantic version tag `vX.Y.Z` in new releases.

GitHub do advocate the use of major and minor release tags in their [Using tags for release management](https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management) discussion, going so far as to mention moving the tags for new releases:

> * Move the major version tag (such as v1, v2) to point to the Git ref of the current release. For more information, see "Git basics - tagging."

**Comment by IlanCosman** [comment]
Thanks for the tip 😄

**Pull request merged**
