### PR TITLE
Install on macOS

### PR DESCRIPTION
**Pull request by reitzig**
Use `brew`, which doesn't need any further setup.

### CODE REVIEW

**Comment by IlanCosman** [comment]
Hi Raphael, thanks for the PR, I really appreciate it 😄 However, I'm not really convinced that macOS CI is necessary for something as simple as fish plugins. I'll be happy to merge this when I see a convincing use case. Sorry 😞

P.S. Composite actions require a `shell:` defined for ever `run:`, so you'd need to add that.

**Comment by reitzig** [comment]
My use case is [testing a fisher plugin](https://github.com/reitzig/sdkman-for-fish/blob/dev/.github/workflows/test.yml) that's supposed to run on Macs. The extra test run is necessary since macOS doesn't come with GNU tools by default, so it's _very_ easy to write shell scripts that behave weirdly or fail outright on a Mac.

**Comment by IlanCosman** [comment]
Alright sounds good, thanks for demonstrating your use case 👍 I'll just trust you that it works since it's a bit cumbersome to test. Thanks again 😄

**Review by IlanCosman — APPROVED** [review]

**Comment by reitzig** [comment]
Oh my ... thanks, but you shouldn't have trusted me it seems. :see_no_evil: [Doesn't work like this, unfortunately](https://github.com/reitzig/sdkman-for-fish/runs/1747259622?check_suite_focus=true).

[Composite actions don't support `if`](https://github.com/actions/runner/blob/main/docs/adrs/0549-composite-run-steps.md#if-condition) right now, how unfortunate. :( 

Let's try this then: #2

**Pull request merged**
